"""add messages table

Revision ID: add_messages_table
Revises: d1c5e7ce77ed
Create Date: 2025-05-22 13:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_messages_table'
down_revision: Union[str, None] = 'd1c5e7ce77ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
        sa.Column('chat_id', sa.BigInteger(), nullable=False),
        sa.Column('collect_messages', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('last_analyzed', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('chat_id')
    )
    
    op.create_table('messages',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('chat_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('chat_analytics',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('chat_id', sa.BigInteger(), nullable=False),
        sa.Column('analyzed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('result', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_analytics')
    op.drop_table('messages')
    op.drop_table('chat_settings')
    # ### end Alembic commands ### 